project:
  type: book
  output-dir: docs

book:
  title: "Tidyverse code review principles"
  author: "Davis Vaughan"
  repo-url: https://github.com/DavisVaughan/code-review
  repo-branch: main
  repo-actions: [edit, issue]
  chapters:
    - index.qmd
    - collaboration/index.qmd
    - part: reviewer/index.qmd
      chapters:
      - reviewer/purpose.qmd
      - reviewer/aspects.qmd
      - reviewer/navigate.qmd
      - reviewer/speed.qmd
      - reviewer/comments.qmd
      - reviewer/pushback.qmd
    - part: author/index.qmd
      chapters:
      - author/descriptions.qmd
      - author/small.qmd
      - author/handling-comments.qmd

format:
  html:
    theme: cosmo

editor: visual

